package app

import (
	"bytes"
	"log"
	"os"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestUniq(t *testing.T) {
	assert.Equal(t, []string{"a", "b", "c"}, uniq([]string{"a", "b", "c", "b", "a"}))
	assert.Nil(t, uniq(nil))
	assert.Equal(t, []string{}, uniq([]string{}))
	assert.Equal(t, []string{"a"}, uniq([]string{"a"}))
}

func TestShortenDataRace(t *testing.T) {
	r := `
=== RUN   Test_App/two_detectors
2023/06/28 22:00:40 redis client connected to redis [ITC 1]
2023/06/28 22:00:40 redis client connected to redis [ITC 1]
==================
WARNING: DATA RACE
Read at 0x0000038df390 by goroutine 25:
  github.com/foo/bar/baz/logger.Info()
      /home/ec2-user/actions-runner/_work/acme/core/logger/logger.go:43 +0x72
  github.com/foo/bar/baz/kafka.newClusterConsumer.func2()
      /home/ec2-user/actions-runner/_work/acme/foo/cluster_consumer.go:88 +0x58
  github.com/foo/bar/baz/kafka.(*ClusterConsumer).Setup()
      /home/ec2-user/actions-runner/_work/acme/foo/cluster_consumer.go:173 +0x2c2
  github.com/foo/bar/baz/kafka.(*TestConsumerGroup).Consume()
      /home/ec2-user/actions-runner/_work/acme/foo/test_consumer_group.go:43 +0x26c
  github.com/foo/bar/baz/kafka.(*ClusterConsumer).StartConsuming.func3()
      /home/ec2-user/actions-runner/_work/acme/foo/cluster_consumer.go:151 +0x3ef

Previous write at 0x0000038df390 by goroutine 13:
  github.com/foo/bar/baz/logger.Init()
      /home/ec2-user/actions-runner/_work/acme/core/logger/zap.go:57 +0x386
  github.com/foo/bar/acme_detector.(*Detector).Start()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/detector.go:88 +0x104
  github.com/foo/bar/acme_detector.Test_App.func4()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/app_test.go:301 +0x4a6
  testing.tRunner()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1629 +0x47

Goroutine 25 (running) created at:
  github.com/foo/bar/baz/kafka.(*ClusterConsumer).StartConsuming()
      /home/ec2-user/actions-runner/_work/acme/foo/cluster_consumer.go:134 +0x371
  github.com/foo/bar/baz/kafka.(*TestConsumer).StartConsuming()
      <autogenerated>:1 +0x4b
  github.com/foo/bar/acme_detector.(*Detector).Start()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/detector.go:119 +0x89e
  github.com/foo/bar/acme_detector.Test_App.func4()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/app_test.go:301 +0x4a6
  testing.tRunner()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1629 +0x47

Goroutine 13 (running) created at:
  testing.(*T).Run()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1629 +0x805
  github.com/foo/bar/acme_detector.Test_App()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/app_test.go:271 +0x1cac
  testing.tRunner()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1629 +0x47
==================
==================
WARNING: DATA RACE
Read at 0x00c000506620 by goroutine 25:
  go.uber.org/zap.(*Logger).check()
      /home/ec2-user/actions-runner/_work/acme/vendor/go.uber.org/zap/logger.go:291 +0x7c
  go.uber.org/zap.(*Logger).Info()
      /home/ec2-user/actions-runner/_work/acme/vendor/go.uber.org/zap/logger.go:212 +0x51
  github.com/foo/bar/baz/logger.Info()
      /home/ec2-user/actions-runner/_work/acme/core/logger/logger.go:44 +0x173
  github.com/foo/bar/baz/kafka.newClusterConsumer.func2()
      /home/ec2-user/actions-runner/_work/acme/foo/cluster_consumer.go:88 +0x58
  github.com/foo/bar/baz/kafka.(*ClusterConsumer).Setup()
      /home/ec2-user/actions-runner/_work/acme/foo/cluster_consumer.go:173 +0x2c2
  github.com/foo/bar/baz/kafka.(*TestConsumerGroup).Consume()
      /home/ec2-user/actions-runner/_work/acme/foo/test_consumer_group.go:43 +0x26c
  github.com/foo/bar/baz/kafka.(*ClusterConsumer).StartConsuming.func3()
      /home/ec2-user/actions-runner/_work/acme/foo/cluster_consumer.go:151 +0x3ef

Previous write at 0x00c000506620 by goroutine 13:
  go.uber.org/zap.(*Logger).clone()
      /home/ec2-user/actions-runner/_work/acme/vendor/go.uber.org/zap/logger.go:278 +0x65
  go.uber.org/zap.(*Logger).WithOptions()
      /home/ec2-user/actions-runner/_work/acme/vendor/go.uber.org/zap/logger.go:168 +0x31
  go.uber.org/zap.New()
      /home/ec2-user/actions-runner/_work/acme/vendor/go.uber.org/zap/logger.go:77 +0x1ca
  github.com/foo/bar/baz/logger.Init()
      /home/ec2-user/actions-runner/_work/acme/core/logger/zap.go:57 +0x372
  github.com/foo/bar/acme_detector.(*Detector).Start()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/detector.go:88 +0x104
  github.com/foo/bar/acme_detector.Test_App.func4()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/app_test.go:301 +0x4a6
  testing.tRunner()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1629 +0x47

Goroutine 25 (running) created at:
  github.com/foo/bar/baz/kafka.(*ClusterConsumer).StartConsuming()
      /home/ec2-user/actions-runner/_work/acme/foo/cluster_consumer.go:134 +0x371
  github.com/foo/bar/baz/kafka.(*TestConsumer).StartConsuming()
      <autogenerated>:1 +0x4b
  github.com/foo/bar/acme_detector.(*Detector).Start()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/detector.go:119 +0x89e
  github.com/foo/bar/acme_detector.Test_App.func4()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/app_test.go:301 +0x4a6
  testing.tRunner()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1629 +0x47

Goroutine 13 (running) created at:
  testing.(*T).Run()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1629 +0x805
  github.com/foo/bar/acme_detector.Test_App()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/app_test.go:271 +0x1cac
  testing.tRunner()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1629 +0x47
==================
    testing.go:1446: race detected during execution of test
--- FAIL: TestUlinkJsonHandler_AppNotFound (0.01s)
`
	s := shortedDataRace(r)

	assert.Equal(t, `
=== RUN   Test_App/two_detectors
2023/06/28 22:00:40 redis client connected to redis [ITC 1]
2023/06/28 22:00:40 redis client connected to redis [ITC 1]
==================
WARNING: DATA RACE
Read at 0x0000038df390 by goroutine 25:
  github.com/foo/bar/baz/logger.Info()
      /home/ec2-user/actions-runner/_work/acme/core/logger/logger.go:43 +0x72
  github.com/foo/bar/baz/kafka.newClusterConsumer.func2()
      /home/ec2-user/actions-runner/_work/acme/foo/cluster_consumer.go:88 +0x58
  github.com/foo/bar/baz/kafka.(*ClusterConsumer).Setup()
      /home/ec2-user/actions-runner/_work/acme/foo/cluster_consumer.go:173 +0x2c2
  github.com/foo/bar/baz/kafka.(*TestConsumerGroup).Consume()
      /home/ec2-user/actions-runner/_work/acme/foo/test_consumer_group.go:43 +0x26c
  github.com/foo/bar/baz/kafka.(*ClusterConsumer).StartConsuming.func3()
      /home/ec2-user/actions-runner/_work/acme/foo/cluster_consumer.go:151 +0x3ef

Previous write at 0x0000038df390 by goroutine 13:
  github.com/foo/bar/baz/logger.Init()
      /home/ec2-user/actions-runner/_work/acme/core/logger/zap.go:57 +0x386
  github.com/foo/bar/acme_detector.(*Detector).Start()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/detector.go:88 +0x104
  github.com/foo/bar/acme_detector.Test_App.func4()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/app_test.go:301 +0x4a6
  testing.tRunner()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1629 +0x47

Goroutine 25 (running) created at:
  github.com/foo/bar/baz/kafka.(*ClusterConsumer).StartConsuming()
      /home/ec2-user/actions-runner/_work/acme/foo/cluster_consumer.go:134 +0x371
  github.com/foo/bar/baz/kafka.(*TestConsumer).StartConsuming()
      <autogenerated>:1 +0x4b
  github.com/foo/bar/acme_detector.(*Detector).Start()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/detector.go:119 +0x89e
  github.com/foo/bar/acme_detector.Test_App.func4()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/app_test.go:301 +0x4a6
  testing.tRunner()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1629 +0x47

Goroutine 13 (running) created at:
  testing.(*T).Run()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1629 +0x805
  github.com/foo/bar/acme_detector.Test_App()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/app_test.go:271 +0x1cac
  testing.tRunner()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1629 +0x47
==================
==================
...... other data race(s) truncated
`, s)
}

// Update golden tests with `make test-imperfect`.
func Test_imperfect(t *testing.T) {
	var fl flags

	fl.FailureStats = "testdata/failure-stats-imperfect.txt"
	fl.Markdown = true
	fl.Slowest = 30
	fl.Slow = time.Second

	p := newProcessor(fl)
	buf := bytes.NewBuffer(nil)
	p.rep = buf

	for i := 0; i < 8; i++ {
		f := "testdata/test-imperfect" + strconv.Itoa(i) + ".jsonl"

		if err := p.process(f); err != nil {
			log.Fatalf("%s: %s", f, err)
		}
	}

	p.report()

	expected, err := os.ReadFile("testdata/imperfect.md")
	require.NoError(t, err)
	assert.Equal(t, string(expected), buf.String())

	stats, err := os.ReadFile("testdata/failure-stats-imperfect.txt")
	require.NoError(t, err)
	assert.Equal(t, `2 flaky test(s), 3 data race(s)`, strings.TrimSpace(string(stats)))
}

// Update golden tests with `make test-broken`.
func Test_broken(t *testing.T) {
	var fl flags

	fl.FailureStats = "testdata/failure-stats-broken.txt"
	fl.FailedTests = "testdata/failed-broken.txt"
	fl.Markdown = true
	fl.Slowest = 30
	fl.Slow = time.Second

	p := newProcessor(fl)
	buf := bytes.NewBuffer(nil)
	p.rep = buf

	for i := 0; i < 4; i++ {
		f := "testdata/test-broken" + strconv.Itoa(i) + ".jsonl"

		if err := p.process(f); err != nil {
			log.Fatalf("%s: %s", f, err)
		}
	}

	p.report()

	expected, err := os.ReadFile("testdata/broken.md")
	require.NoError(t, err)
	assert.Equal(t, string(expected), buf.String())

	stats, err := os.ReadFile("testdata/failure-stats-broken.txt")
	require.NoError(t, err)
	assert.Equal(t, `2 package(s) failed build, 3 failed test(s), 2 unfinished test(s)`, strings.TrimSpace(string(stats)))

	failedRegex, err := os.ReadFile("testdata/failed-broken.txt")
	require.NoError(t, err)
	assert.Equal(t, `^TestAlwaysFails$|^TestAlwaysFailsInSubtest$|^TestAlwaysFailsInSubtest//-|^TestThatPanics$|^TestThatPanicsInAGoroutine$`, strings.TrimSpace(string(failedRegex)))
}
