package app

import (
	"bufio"
	"bytes"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// globRetryFiles finds every "testdata/<prefix>N.jsonl" round file, in the same lexical order
// run-imperfect.sh/run-broken.sh's own final `... test-imperfect*.jsonl` bash glob expansion
// processes them in (filepath.Glob already returns matches sorted that way, matching bash's
// default). That order matters, not just for reproducing the committed golden file byte-for-byte:
// a package's reported Elapsed is overwritten, not summed, by each file processed (see pkgLine),
// so processing order changes which round's duration ends up in the final report. The retry
// loops themselves converge as soon as a round has no more failures, so the actual number of
// rounds recorded varies run to run (usually well under their 20/3-round ceiling) -- a hardcoded
// loop count breaks the moment a regeneration happens to converge faster or slower than whatever
// count was hardcoded last time.
func globRetryFiles(t *testing.T, prefix string) []string {
	t.Helper()

	matches, err := filepath.Glob("testdata/" + prefix + "*.jsonl")
	require.NoError(t, err)
	require.NotEmpty(t, matches, "no %sN.jsonl files found; run `make %s` first", prefix, prefix)

	return matches
}

func TestUniq(t *testing.T) {
	assert.Equal(t, []string{"a", "b", "c"}, uniq([]string{"a", "b", "c", "b", "a"}))
	assert.Nil(t, uniq(nil))
	assert.Equal(t, []string{}, uniq([]string{}))
	assert.Equal(t, []string{"a"}, uniq([]string{"a"}))
}

func TestShortenDataRace(t *testing.T) {
	r := `
=== RUN   Test_App/two_detectors
2023/06/28 22:00:40 redis client connected to redis [ITC 1]
2023/06/28 22:00:40 redis client connected to redis [ITC 1]
==================
WARNING: DATA RACE
Read at 0x0000038df390 by goroutine 25:
  github.com/foo/bar/baz/logger.Info()
      /home/ec2-user/actions-runner/_work/acme/core/logger/logger.go:43 +0x72
  github.com/foo/bar/baz/kafka.newClusterConsumer.func2()
      /home/ec2-user/actions-runner/_work/acme/foo/cluster_consumer.go:88 +0x58
  github.com/foo/bar/baz/kafka.(*ClusterConsumer).Setup()
      /home/ec2-user/actions-runner/_work/acme/foo/cluster_consumer.go:173 +0x2c2
  github.com/foo/bar/baz/kafka.(*TestConsumerGroup).Consume()
      /home/ec2-user/actions-runner/_work/acme/foo/test_consumer_group.go:43 +0x26c
  github.com/foo/bar/baz/kafka.(*ClusterConsumer).StartConsuming.func3()
      /home/ec2-user/actions-runner/_work/acme/foo/cluster_consumer.go:151 +0x3ef

Previous write at 0x0000038df390 by goroutine 13:
  github.com/foo/bar/baz/logger.Init()
      /home/ec2-user/actions-runner/_work/acme/core/logger/zap.go:57 +0x386
  github.com/foo/bar/acme_detector.(*Detector).Start()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/detector.go:88 +0x104
  github.com/foo/bar/acme_detector.Test_App.func4()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/app_test.go:301 +0x4a6
  testing.tRunner()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1629 +0x47

Goroutine 25 (running) created at:
  github.com/foo/bar/baz/kafka.(*ClusterConsumer).StartConsuming()
      /home/ec2-user/actions-runner/_work/acme/foo/cluster_consumer.go:134 +0x371
  github.com/foo/bar/baz/kafka.(*TestConsumer).StartConsuming()
      <autogenerated>:1 +0x4b
  github.com/foo/bar/acme_detector.(*Detector).Start()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/detector.go:119 +0x89e
  github.com/foo/bar/acme_detector.Test_App.func4()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/app_test.go:301 +0x4a6
  testing.tRunner()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1629 +0x47

Goroutine 13 (running) created at:
  testing.(*T).Run()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1629 +0x805
  github.com/foo/bar/acme_detector.Test_App()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/app_test.go:271 +0x1cac
  testing.tRunner()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1629 +0x47
==================
==================
WARNING: DATA RACE
Read at 0x00c000506620 by goroutine 25:
  go.uber.org/zap.(*Logger).check()
      /home/ec2-user/actions-runner/_work/acme/vendor/go.uber.org/zap/logger.go:291 +0x7c
  go.uber.org/zap.(*Logger).Info()
      /home/ec2-user/actions-runner/_work/acme/vendor/go.uber.org/zap/logger.go:212 +0x51
  github.com/foo/bar/baz/logger.Info()
      /home/ec2-user/actions-runner/_work/acme/core/logger/logger.go:44 +0x173
  github.com/foo/bar/baz/kafka.newClusterConsumer.func2()
      /home/ec2-user/actions-runner/_work/acme/foo/cluster_consumer.go:88 +0x58
  github.com/foo/bar/baz/kafka.(*ClusterConsumer).Setup()
      /home/ec2-user/actions-runner/_work/acme/foo/cluster_consumer.go:173 +0x2c2
  github.com/foo/bar/baz/kafka.(*TestConsumerGroup).Consume()
      /home/ec2-user/actions-runner/_work/acme/foo/test_consumer_group.go:43 +0x26c
  github.com/foo/bar/baz/kafka.(*ClusterConsumer).StartConsuming.func3()
      /home/ec2-user/actions-runner/_work/acme/foo/cluster_consumer.go:151 +0x3ef

Previous write at 0x00c000506620 by goroutine 13:
  go.uber.org/zap.(*Logger).clone()
      /home/ec2-user/actions-runner/_work/acme/vendor/go.uber.org/zap/logger.go:278 +0x65
  go.uber.org/zap.(*Logger).WithOptions()
      /home/ec2-user/actions-runner/_work/acme/vendor/go.uber.org/zap/logger.go:168 +0x31
  go.uber.org/zap.New()
      /home/ec2-user/actions-runner/_work/acme/vendor/go.uber.org/zap/logger.go:77 +0x1ca
  github.com/foo/bar/baz/logger.Init()
      /home/ec2-user/actions-runner/_work/acme/core/logger/zap.go:57 +0x372
  github.com/foo/bar/acme_detector.(*Detector).Start()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/detector.go:88 +0x104
  github.com/foo/bar/acme_detector.Test_App.func4()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/app_test.go:301 +0x4a6
  testing.tRunner()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1629 +0x47

Goroutine 25 (running) created at:
  github.com/foo/bar/baz/kafka.(*ClusterConsumer).StartConsuming()
      /home/ec2-user/actions-runner/_work/acme/foo/cluster_consumer.go:134 +0x371
  github.com/foo/bar/baz/kafka.(*TestConsumer).StartConsuming()
      <autogenerated>:1 +0x4b
  github.com/foo/bar/acme_detector.(*Detector).Start()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/detector.go:119 +0x89e
  github.com/foo/bar/acme_detector.Test_App.func4()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/app_test.go:301 +0x4a6
  testing.tRunner()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1629 +0x47

Goroutine 13 (running) created at:
  testing.(*T).Run()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1629 +0x805
  github.com/foo/bar/acme_detector.Test_App()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/app_test.go:271 +0x1cac
  testing.tRunner()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1629 +0x47
==================
    testing.go:1446: race detected during execution of test
--- FAIL: TestUlinkJsonHandler_AppNotFound (0.01s)
`
	s := shortedDataRace(r)

	assert.Equal(t, `
=== RUN   Test_App/two_detectors
2023/06/28 22:00:40 redis client connected to redis [ITC 1]
2023/06/28 22:00:40 redis client connected to redis [ITC 1]
==================
WARNING: DATA RACE
Read at 0x0000038df390 by goroutine 25:
  github.com/foo/bar/baz/logger.Info()
      /home/ec2-user/actions-runner/_work/acme/core/logger/logger.go:43 +0x72
  github.com/foo/bar/baz/kafka.newClusterConsumer.func2()
      /home/ec2-user/actions-runner/_work/acme/foo/cluster_consumer.go:88 +0x58
  github.com/foo/bar/baz/kafka.(*ClusterConsumer).Setup()
      /home/ec2-user/actions-runner/_work/acme/foo/cluster_consumer.go:173 +0x2c2
  github.com/foo/bar/baz/kafka.(*TestConsumerGroup).Consume()
      /home/ec2-user/actions-runner/_work/acme/foo/test_consumer_group.go:43 +0x26c
  github.com/foo/bar/baz/kafka.(*ClusterConsumer).StartConsuming.func3()
      /home/ec2-user/actions-runner/_work/acme/foo/cluster_consumer.go:151 +0x3ef

Previous write at 0x0000038df390 by goroutine 13:
  github.com/foo/bar/baz/logger.Init()
      /home/ec2-user/actions-runner/_work/acme/core/logger/zap.go:57 +0x386
  github.com/foo/bar/acme_detector.(*Detector).Start()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/detector.go:88 +0x104
  github.com/foo/bar/acme_detector.Test_App.func4()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/app_test.go:301 +0x4a6
  testing.tRunner()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1629 +0x47

Goroutine 25 (running) created at:
  github.com/foo/bar/baz/kafka.(*ClusterConsumer).StartConsuming()
      /home/ec2-user/actions-runner/_work/acme/foo/cluster_consumer.go:134 +0x371
  github.com/foo/bar/baz/kafka.(*TestConsumer).StartConsuming()
      <autogenerated>:1 +0x4b
  github.com/foo/bar/acme_detector.(*Detector).Start()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/detector.go:119 +0x89e
  github.com/foo/bar/acme_detector.Test_App.func4()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/app_test.go:301 +0x4a6
  testing.tRunner()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1629 +0x47

Goroutine 13 (running) created at:
  testing.(*T).Run()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1629 +0x805
  github.com/foo/bar/acme_detector.Test_App()
      /home/ec2-user/actions-runner/_work/acme/quux/acme_detector/app_test.go:271 +0x1cac
  testing.tRunner()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /home/ec2-user/actions-runner/_work/_tool/go/1.20.4/x64/src/testing/testing.go:1629 +0x47
==================
==================
...... other data race(s) truncated
`, s)
}

// Update golden tests with `make test-imperfect`.
func Test_imperfect(t *testing.T) {
	var fl flags

	fl.FailureStats = "testdata/failure-stats-imperfect.txt"
	fl.Markdown = true
	fl.Slowest = 30
	fl.Slow = time.Second

	p := newProcessor(fl)
	buf := bytes.NewBuffer(nil)
	p.rep = buf

	for _, f := range globRetryFiles(t, "test-imperfect") {
		if err := p.process(f); err != nil {
			log.Fatalf("%s: %s", f, err)
		}
	}

	p.report()

	expected, err := os.ReadFile("testdata/imperfect.md")
	require.NoError(t, err)
	assert.Equal(t, string(expected), buf.String())

	stats, err := os.ReadFile("testdata/failure-stats-imperfect.txt")
	require.NoError(t, err)
	assert.Equal(t, `2 flaky test(s)`, strings.TrimSpace(string(stats)))
}

// Update golden tests with `make test-broken`.
func Test_broken(t *testing.T) {
	var fl flags

	fl.FailureStats = "testdata/failure-stats-broken.txt"
	fl.FailedTests = "testdata/failed-broken.txt"
	fl.Markdown = true
	fl.Slowest = 30
	fl.Slow = time.Second

	p := newProcessor(fl)
	buf := bytes.NewBuffer(nil)
	p.rep = buf

	for _, f := range globRetryFiles(t, "test-broken") {
		if err := p.process(f); err != nil {
			log.Fatalf("%s: %s", f, err)
		}
	}

	p.report()

	expected, err := os.ReadFile("testdata/broken.md")
	require.NoError(t, err)
	assert.Equal(t, string(expected), buf.String())

	stats, err := os.ReadFile("testdata/failure-stats-broken.txt")
	require.NoError(t, err)
	assert.Equal(t, `3 package(s) failed build, 3 failed test(s), 2 unfinished test(s)`, strings.TrimSpace(string(stats)))

	failedRegex, err := os.ReadFile("testdata/failed-broken.txt")
	require.NoError(t, err)
	assert.Equal(t, `^TestAlwaysFails$|^TestAlwaysFailsInSubtest$|^TestAlwaysFailsInSubtest//-|^TestThatPanics$|^TestThatPanicsInAGoroutine$`, strings.TrimSpace(string(failedRegex)))
}

// Test_cachemiss runs the cachemiss scenario live, twice, against a shared temp GOCACHE, rather
// than replaying a committed fixture the way Test_imperfect/Test_broken do: the testcache
// trace's file path is absolute, baked in at capture time by go itself, so a fixture recorded on
// one machine can't be relativized correctly when replayed on another (e.g. CI) -- see
// inputFilePath/relativeTo, which relativizes against wherever *this* process is running from,
// not wherever the trace was originally captured. Running live keeps that path always consistent
// with the current checkout. Chdir'd to the repo root (like run-cachemiss.sh) so that path comes
// out as the clean "cachemiss/marker.txt" a real invocation from the repo root would show,
// instead of an artifact of this test binary's own package directory.
func Test_cachemiss(t *testing.T) {
	t.Chdir("..")

	env := append(os.Environ(), "GOCACHE="+t.TempDir(), "GODEBUG=gocachetest=1")

	var fl flags
	fl.Markdown = true

	p := newProcessor(fl)
	buf := bytes.NewBuffer(nil)
	p.rep = buf

	for i := range 2 {
		cmd := exec.Command("go", "test", "-tags", "cachemiss", "-json", "./cachemiss/...")
		cmd.Env = env

		var out bytes.Buffer
		cmd.Stdout = &out
		cmd.Stderr = &out

		require.NoError(t, cmd.Run(), "round %d: %s", i, out.String())

		scanner := bufio.NewScanner(&out)
		scanner.Buffer(make([]byte, 0, 1e7), 1e7)
		require.NoError(t, p.iterate(scanner))
	}

	t.Cleanup(func() {
		if err := os.Remove(filepath.Join("cachemiss", "marker.txt")); err != nil && !os.IsNotExist(err) {
			t.Logf("remove marker.txt: %s", err)
		}
	})

	p.report()

	out := buf.String()
	require.Contains(t, out, "Packages: 1 total, 0 cached, 1 miss, 0 failing, 0 no tests")
	require.Contains(t, out, "miss: no prior cached result found")
	require.Contains(t, out, "miss: input file too new: "+filepath.Join("cachemiss", "marker.txt"))
}

func TestReportTestCache_SkipsSectionWhenNoMissHasAReason(t *testing.T) {
	var fl flags
	fl.Markdown = true

	p := newProcessor(fl)
	buf := bytes.NewBuffer(nil)
	p.rep = buf

	// A miss with no testcache trace captured at all (testcacheSeen stays false, so
	// cacheStats never even adds the noReasonLogged placeholder): nothing actionable to show.
	p.packageStats["example.com/pkg"] = packageStat{Package: "example.com/pkg", HadTests: true}

	p.reportTestCache()

	require.Empty(t, buf.String(), "a report with nothing actionable to say shouldn't print anything")
}

func TestReportTestCache_SkipsSectionWhenOnlyPlaceholderReasons(t *testing.T) {
	var fl flags
	fl.Markdown = true

	p := newProcessor(fl)
	buf := bytes.NewBuffer(nil)
	p.rep = buf

	// A trace WAS captured (testcacheSeen=true), but produced no specific finding for this
	// package -- still nothing actionable, just from a different code path than the case above.
	p.packageStats["example.com/pkg"] = packageStat{Package: "example.com/pkg", HadTests: true}
	p.testcacheSeen = true

	p.reportTestCache()

	require.Empty(t, buf.String())
}

func TestReportTestCache_ShowsSectionWhenAtLeastOneMissHasAReason(t *testing.T) {
	var fl flags
	fl.Markdown = true

	p := newProcessor(fl)
	buf := bytes.NewBuffer(nil)
	p.rep = buf

	p.packageStats["example.com/pkg"] = packageStat{Package: "example.com/pkg", HadTests: true}
	p.testcacheFindings["example.com/pkg"] = []testcacheReason{
		{Package: "example.com/pkg", Reason: "miss: no prior cached result found"},
	}

	p.reportTestCache()

	out := buf.String()
	require.Contains(t, out, "### Test cache")
	require.Contains(t, out, "miss: no prior cached result found")
}

func addColdMisses(p *processor, n int) {
	for i := range n {
		pkg := fmt.Sprintf("example.com/pkg%03d", i)
		p.packageStats[pkg] = packageStat{Package: pkg, HadTests: true}
		p.testcacheFindings[pkg] = []testcacheReason{
			{Package: pkg, Reason: "miss: no prior cached result found"},
		}
	}
}

func TestReportTestCache_TruncatesMarkdownListOnColdRun(t *testing.T) {
	var fl flags
	fl.Markdown = true

	p := newProcessor(fl)
	buf := bytes.NewBuffer(nil)
	p.rep = buf

	addColdMisses(p, maxReportedMisses+10)

	p.reportTestCache()

	out := buf.String()
	require.Contains(t, out, fmt.Sprintf("Cache misses: %d", maxReportedMisses+10))
	require.Contains(t, out, "| ... | 10 more not shown |")
	require.Equal(t, maxReportedMisses, strings.Count(out, "miss: no prior cached result found"),
		"only the first maxReportedMisses rows should actually be printed")
}

func TestReportTestCache_TruncatesPlainListOnColdRun(t *testing.T) {
	var fl flags

	p := newProcessor(fl)
	buf := bytes.NewBuffer(nil)
	p.rep = buf

	addColdMisses(p, maxReportedMisses+1)

	p.reportTestCache()

	out := buf.String()
	require.Contains(t, out, "... 1 more not shown")
	require.Equal(t, maxReportedMisses, strings.Count(out, "miss: no prior cached result found"))
}

func TestReportTestCache_NoTruncationNoteWhenUnderLimit(t *testing.T) {
	var fl flags
	fl.Markdown = true

	p := newProcessor(fl)
	buf := bytes.NewBuffer(nil)
	p.rep = buf

	addColdMisses(p, maxReportedMisses)

	p.reportTestCache()

	require.NotContains(t, buf.String(), "more not shown")
}
